pet-charity-be-feature/registration - created user route/schema
alexander-svirzhevsky/pet-charity-be pull request #1
Opened 2021-04-16 11:38 UTC by alexander-svirzhevsky

Realized a registration

2021-04-17 18:53 UTC, universezzz requested changes

2021-04-17 18:53 UTC, universezzz commented on config/default.json
> +    "mongoURI": "mongodb+srv://alexander123:alexander123@cluster.7nzur.mongodb.net/myFirstDatabase?retryWrites=true&w=majority",
Why is your secret config public? :DDD

2021-04-17 18:53 UTC, universezzz commented on routes/api/users.js
> +// @access    Publick
Publick :DD
Remove all those comments, you'll add swagger soon, you don't need this anymore.

P.S.
// @route     POST api/users
// @desc      Register user
// @access    Publick 
remove this everywhere

2021-04-17 18:53 UTC, universezzz commented on routes/api/users.js
> +const User = require("../../db/Schema/User");
always separate libraries and your imports. It makes your code clean and more readable
e.g. 
`
const express = require("express");
const router = express.Router();
const { check, validationResult } = require("express-validator");
const config = require("config");
const gravatar = require("gravatar");
const argon2 = require("argon2");
const jwt = require("jsonwebtoken");

const User = require("../../db/Schema/User");
`

2021-04-17 18:53 UTC, universezzz commented on routes/api/users.js
> +const gravatar = require("gravatar");
you don't need gravatar at all, remove this package (npm unistall gravatar). It's a reason why I told you create a separate branch for FE/BE initial structure.

2021-04-17 18:53 UTC, universezzz commented on routes/api/users.js
> +      // See if user exists
get rid of it

2021-04-17 18:53 UTC, universezzz commented on routes/api/users.js
> +      });
get rid of it

2021-04-17 18:53 UTC, universezzz commented on db/Schema/User.js
> +  },
get rid of it

2021-04-17 18:53 UTC, universezzz commented on routes/api/users.js
> +      // Encrypt password Argon2
get rid of it

2021-04-17 18:53 UTC, universezzz commented on routes/api/users.js
> +      await argon2.hash(password);
wtf is this? You must store **hashed** password in database. But you create an user on lane 48, and after that just hash password, you don't even get result from argon2.hash function. 

`
const hashedPassword = await argon2.hash(password);

user = new User({
  name,
  email,
  password: hashedPassword,
});
      
await user.save();
`

2021-04-17 18:53 UTC, universezzz commented on routes/api/users.js
> +    }
You have to create a **The default error handler**
https://expressjs.com/en/guide/error-handling.html

2021-04-17 18:53 UTC, universezzz commented on server.js
> +// Connect Database
get rid of it

2021-04-17 18:53 UTC, universezzz commented on server.js
>  const PORT = 5000;
const PORT = process.env.PORT || 5000;
In production build you'll specify port based on environment variable.

2021-04-17 18:53 UTC, universezzz commented on server.js
>  });
get rid of it

2021-04-17 19:00 UTC, alexander-svirzhevsky commented on config/default.json
> +    "mongoURI": "mongodb+srv://alexander123:alexander123@cluster.7nzur.mongodb.net/myFirstDatabase?retryWrites=true&w=majority",
where should he be? :)

2021-04-18 11:13 UTC, alexander-svirzhevsky commented on config/default.json
> +    "mongoURI": "mongodb+srv://alexander123:alexander123@cluster.7nzur.mongodb.net/myFirstDatabase?retryWrites=true&w=majority",
add config folder in gitignore

2021-04-18 11:13 UTC, alexander-svirzhevsky commented on routes/api/users.js
> +// @access    Publick
remove all comments

2021-04-18 11:14 UTC, alexander-svirzhevsky commented on routes/api/users.js
> +const User = require("../../db/Schema/User");
separate libraries and my imports

2021-04-18 11:17 UTC, alexander-svirzhevsky commented on routes/api/users.js
> +const gravatar = require("gravatar");
uninstall gravatar

2021-04-18 11:18 UTC, alexander-svirzhevsky commented on routes/api/users.js
> +      // See if user exists
remove all comments

2021-04-18 11:20 UTC, alexander-svirzhevsky commented on routes/api/users.js
> +      await argon2.hash(password);
got it, my mistake ....

2021-04-18 11:40 UTC, alexander-svirzhevsky commented on server.js
> +// Connect Database
got it

2021-04-18 11:45 UTC, alexander-svirzhevsky commented on server.js
>  const PORT = 5000;
got it, and fixed it

2021-04-18 11:45 UTC, alexander-svirzhevsky commented on server.js
>  });
ok

2021-04-18 12:02 UTC, alexander-svirzhevsky commented on routes/api/users.js
> +    }
"is added at the end of the middleware function stack" 
using this i fixed problem, but not shure if it's right
![users js - pet-charity-be - Visual Studio Code  Ad](https://user-images.githubusercontent.com/69677247/115144761-1c294e00-a057-11eb-9399-c4f05bad3914.png)

2021-04-19 07:06 UTC, merged